name: Code Quality Check

on:
  push:
    branches: [dev]  # Runs on direct pushes to dev
  pull_request:
    branches: [dev]  # Runs on PRs to dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Install dependencies
        run: pip install flake8
      
      - name: Run Flake8
        run: flake8 .
